<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verif_Halaman_KonfirmasiPesanan</name>
   <tag></tag>
   <elementGuidId>1af3b408-e27e-4580-8e99-e5bb138b6682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout_complete_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;checkout-complete-container&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bfc988c-438c-42c1-8cd4-dd12e8c52a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>47e96504-e019-4b83-abd1-e63094eab4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>261ed085-c15c-4441-8e81-daecb0f1bf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>checkout-complete-container</value>
      <webElementGuid>76c95ee9-bb26-422e-be3d-48618d431ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home</value>
      <webElementGuid>17ffc627-7132-42f1-9176-131d1c18e11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)</value>
      <webElementGuid>0c47f233-3c53-466a-ac81-d03d05273c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']</value>
      <webElementGuid>29624005-aa3a-4b40-b4f7-209655f862a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>f82f8f7b-5a67-49be-8db1-54f7c9fdf4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout: Complete!'])[1]/following::div[1]</value>
      <webElementGuid>248ec299-d0a6-4c71-b51b-f25d18f62532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[3]</value>
      <webElementGuid>406eeef5-946b-49f4-8083-d416d83f0c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>4132fd48-3c42-4a18-9820-2d9f5cbc2202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkout_complete_container' and (text() = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home' or . = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home')]</value>
      <webElementGuid>f4e1be76-157c-4daf-bdc8-5654aeb442ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
